schema_version = "1.0.0"
id = "separate_by_collision"
name = "Separate by Collision"
version = "2.0.1"
tagline = "Separate by loose parts, but parts are joined if they collide"
maintainer = "Hattiffnat"
type = "add-on"
tags = ["Mesh", "Object"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/Hattiffnat/SeparateByCollision"
platforms = ["linux-x64", "windows-x64", "macos-arm64", "macos-x64"]
