schema_version = "1.0.0"
id = "separate_by_collision"
name = "Separate by Collision"
version = "1.0.2"
tagline = "Separate mesh by loose parts. Parts are grouped if they collide"
maintainer = "Hattiffnat"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/Hattiffnat/SeparateByCollision"
