name: Release
env:
  ARCHIVE_NAME: separate_by_collision

on:
  release:
    types: [prereleased, edited]

jobs:
  build-and-upload-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64
          rustup target add x86_64-pc-windows-gnu
          cargo install cargo-zigbuild

      - name: Create archive
        run: |
          make build-extension-archive-release

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./extension_release/${{ env.ARCHIVE_NAME }}_extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
